# Generated by Django 4.1.5 on 2023-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_user_email_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название симптома')),
                ('description', models.CharField(max_length=255, verbose_name='описание симптома')),
                ('doctor', models.CharField(max_length=255, verbose_name='лечащий врач')),
            ],
        ),
    ]
